# Introduction

NumPy stands for Numerical Python and it's a fundamental package for scientific computing in Python. NumPy provides Python with an extensive math library capable of performing numerical computations effectively and efficiently.

<u>Overview</u>

* How to import NumPy
+ How to create multidimensional NumPy ndarrays using various methods
- How to access and change elements in ndarrays
- How to load and save ndarrays
+ How to use slicing to select or change subsets of an ndarray
* Understand the difference between a view and a copy an of ndarray
* How to use Boolean indexing and set operations to select or change subsets of an ndarray
* How to sort ndarrays
* How to perform element-wise operations on ndarrays
+ Understand how NumPy uses broadcasting to perform operations on ndarrays of different sizes.


You can check which version of NumPy you have by typing *!conda list numpy* in your Jupyter Notebook or by typing *conda list numpy* in the Anaconda prompt.


For more indepth study of numpy:

* [NumPy Manual](https://docs.scipy.org/doc/numpy-1.13.0/contents.html)
* [NumPy User Guide](https://docs.scipy.org/doc/numpy-1.13.0/user/index.html)
+ [NumPy Reference](https://docs.scipy.org/doc/numpy-1.13.0/reference/index.html#reference)
- [Scipy Lectures](http://scipy-lectures.org/intro/numpy/index.html)



One of the key features that Numpy has over python list is speed. When performing operations on large arrays, NumPy can often perform several orders of magnitude faster than Python lists. This speed comes from the nature of NumPy arrays being *memory-efficient* and from *optimized algorithms* used by NumPy for doing:
* arithmetic operations
+ statistical operations
- linear algebra operations

Another great feature of NumPy is that it has multidimensional array data structures that can represent:
+ vectors
- matrices (a lot of machine learning algorithms rely on matrix operations). For example, when training a Neural Network, you often have to carry out many matrix multiplications. NumPy is optimized for matrix operations and it allows us to do Linear Algebra operations effectively and efficiently, making it very suitable for solving machine learning problems.

Another great advantage of NumPy over Python lists is that NumPy has a large number of optimized built-in mathematical functions. These functions allow you to do a variety of complex mathematical computations very fast and with very little code (avoiding the use of complicated loops) making your programs more readable and easier to understand.

Yet another great advantage of NumPy is that it can handle more data-types than Python lists. You can check out all the different data types NumPy supports in the link below: [NumPy Data Types](https://docs.scipy.org/doc/numpy-1.13.0/user/basics.types.html)

**Summary:** NumPy is fast, NumPy has multidimensional array data structures, and it has a large number of optimized built-in mathematical functions.

NumPy has become so popular that a lot of Python packages, such as **Pandas**, are built on top of NumPy.

# Creating and Saving Numpy Arrays

At the core of NumPy is the *ndarray*, where *nd* stands for *n-dimensional*. An ndarray is a *multidimensional array* of elements all of the same type. In other words, an ndarray is a grid that can take on many shapes and can hold either numbers or strings. In many Machine Learning problems you will often find yourself using ndarrays in many different ways. For instance, you might use an ndarray to hold the pixel values of an image that will be fed into a Neural Network for image classification.

Numpy arrays are created using:
1. Numpy array function to create them from other array like objects such as regular python list
2. Using a variety of built-in NumPy functions that quickly generates specific types of NumPy arrays

In [5]:
#1. Creating from a python list
import numpy as np
my_list = [1, 2, 3, 4, 5]
np.array(my_list)

array([1, 2, 3, 4, 5])

In [6]:
#2. This is a one dimensional array
x = np.array([1, 2, 3, 4, 5])
x

array([1, 2, 3, 4, 5])

The shape of an array is the size along each of its dimensions. For example, the shape of a *rank 2* array will correspond to the number of rows and columns of the array. For example, the shape of an ndarray can be obtained using the *.shape()* attribute.

The shape attribute returns a tuple of N positive integers that specify the sizes of each dimension. the *.dtype()* attribute tells us that the elements of x are stored in memory as signed 32-bit integers.In the example below we will create a *rank 1* array and learn how to obtain its shape, its type, and the data-type (dtype) of its elements.

In [7]:
print(type(x)) #returns the type of the array
print(x.dtype) #returns the type of the elements in the array. It is a 32bit int
print(x.shape) #returns a tuple of n-positive integers that specifies the length of the array
#If this was a 2-dimensional array, the shape method will return 2 values (rows and columns)

<class 'numpy.ndarray'>
int32
(5,)


In [8]:
# This is a two dimensional array
y = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
print(y)
y.shape

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


(4, 3)

In [9]:
y.size #gives us the total number of elements in y

12

Generally, an array with n-dimension is seen as a *rank n*. The 1D array (x) we created earlier is seen as a *rank* 1 array while the second is a 2D array (y) is konwn as a *rank* 2 array. Let's go ahead to create a 1D array using string.

In [10]:
z = np.array(["Hello", "World"])
print(z)
print("Type:", type(z))
print("D.Type:", z.dtype) #it returns a unicode string of 5 characters
print("Shape:", z.shape)
print("Size:", z.size)

['Hello' 'World']
Type: <class 'numpy.ndarray'>
D.Type: <U5
Shape: (2,)
Size: 2


In [11]:
#let's create one with mixed data type
a = np.array([1, "Hello", "World", 2])
print(a)
print("Type:", type(a))
print("D.Type:", a.dtype) #it returns a unicode string of 11 characters.
print("Shape:", a.shape)
print("Size:", a.size) #gives the number of the element in the array

['1' 'Hello' 'World' '2']
Type: <class 'numpy.ndarray'>
D.Type: <U11
Shape: (4,)
Size: 4


the .dtype attribute tells us that the elements in a are stored in memory as Unicode strings of 11 characters.

It is important to remember that one big difference between Python lists and ndarrays, is that unlike Python lists, all the elements of an ndarray must be of the same type.

While we can create Python lists with both integers and strings, we can't mix types in ndarrays. If you provide the np.array() function with a Python list that has both integers and strings, NumPy will interpret all elements as strings. We can see this in the example above.

In [12]:
b = np.array([1, 2.5, 3.2, 4])
c = np.array([1.1, 2.2, 4.5, 5.6])
print(b, x.dtype)
print(c, c.dtype)

[1.  2.5 3.2 4. ] int32
[1.1 2.2 4.5 5.6] float64



We can see that when we create an ndarray with only floats, NumPy stores the elements in memory as *64-bit floating point numbers (float64)*. However, notice that when we create an ndarray with both floats and integers, as we did with the b ndarray above, NumPy assigns its elements a *float64* dtype as well. This is called upcasting. Since all the elements of an ndarray must be of the same type, in this case NumPy upcasts the integers in b to floats(will look into why the code above produced otherwise) in order to avoid losing precision in numerical computations.

Even though NumPy automatically selects the dtype of the ndarray, NumPy also allows you to specify the particular dtype you want to assign to the elements of the ndarray. You can specify the dtype when you create the ndarray using the keyword dtype in the *np.array()* function

Here is an example below:

In [13]:
d = np.array([1.5, 2.2, 3.7], dtype=np.int64)
print(d)
print("DType:", d.dtype)

[1 2 3]
DType: int64


We can see that even though we created the ndarray with floats, by specifying the dtype to be int64, NumPy converted the floating point numbers into integers by removing their decimals. 

You do this when:
+ you don't want NumPy to accidentaly choose the wrong data type or 
* you only need a specified amount of precision in your calculations and want to save memory.

#### Saving NumPy array
Numpy has a way of saving data to a file to be read later or to be used by another program. it does this with the *np.save* function. This file can later be loaded using the *np.load* function. 

When loading an array from a file, make sure you include the name of the file together with the extension *.npy*, otherwise you will get an error.

Let's see an example

In [14]:
np.save("my_first_np_array", x)

In [15]:
np.load("my_first_np_array.npy")

array([1, 2, 3, 4, 5])

# Using Built-in Functions to Create ndarrays 

One great time-saving feature of NumPy is its ability to create ndarrays using built-in functions. These functions allow us to create certain kinds of ndarrays with just one line of code. This method is very popular in AI programming.

Let's start by creating an ndarray with a specified shape that is full of zeros. We can do this by using the *np.zeros()* function. The function *np.zeros(shape)* creates an ndarray full of zeros with the given shape. So, for example, if you wanted to create a *rank 2* array with *3 rows and 4 columns*, you will pass the shape to the function in the form of (rows, columns), as in the example below:

In [16]:
# We create a 3 x 4 ndarray full of zeros. 
e = np.zeros((3,4))

# We print e
print()
print(e)
print()

# We print information about e
print('e has', e.shape, 'dimensions')
print('e is an object of type:', type(e))
print('The elements in e are of the', e.dtype, 'type')


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

e has (3, 4) dimensions
e is an object of type: <class 'numpy.ndarray'>
The elements in e are of the float64 type


As we can see, the np.zeros() function creates by default an array with dtype float64. If desired, the data type can be changed by using the keyword dtype. let's see an example below:

In [17]:
f = np.zeros((3,4), dtype=np.int64)
print(f, "\n")
print(f.dtype)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]] 

int64


In [18]:
# we can also try out np.ones too

g = np.ones((5,4))
print(g)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


We can also create an ndarray with a specified shape that is full of any number we want. We can do this by using the np.full() function. The **np.full(shape, constant value)** function takes two arguments. The first argument is the shape of the ndarray you want to make and the second is the constant value you want to populate the array with. Let's see an example:

In [19]:
# We create a 2 x 3 ndarray full of fives. 
h = np.full((4,7), 5) 

print(h, "\n")

# We print information about h
print("h has", h.shape, "dimensions", "\n")
print("h is a",  type(h), "object", "\n")
print("The elements in h are", h.dtype)

[[5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5]] 

h has (4, 7) dimensions 

h is a <class 'numpy.ndarray'> object 

The elements in h are int32


There is a fundamental array in Linear Algebra called the *Identity Matrix*. An Identity matrix is a *square matrix* that has only 1s in its main diagonal and zeros everywhere else. 

The function *np.eye(N)* creates a square N x N ndarray corresponding to the Identity matrix. Since all Identity Matrices are square, the *np.eye()* function only takes a single integer as an argument. Let's see an example: 

In [20]:
# We create a 5 x 5 Identity matrix. 
I = np.eye(5)

# We print I
print()
print('I = \n', I)
print()

# We print information about I
print('I has dimensions:', I.shape)
print('I is an object of type:', type(I))
print('The elements in I are of type:', I.dtype)


I = 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

I has dimensions: (5, 5)
I is an object of type: <class 'numpy.ndarray'>
The elements in I are of type: float64


We can also create diagonal matrices by using the np.diag() function. A diagonal matrix is a square matrix that only has values in its main diagonal. The *np.diag()* function creates an ndarray corresponding to a diagonal matrix.

In [21]:
# Create a 4 x 4 diagonal matrix that contains the numbers 10,20,30, and 50
# on its main diagonal
j = np.diag([10,20,30,50])

# We print X
print(j, "\n")


# We print information about I
print('j has', j.shape, 'dimensions', "\n")
print('j is an object of type:', type(j), "\n")
print('The elements in j are', j.dtype, 'type', "\n")

[[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 50]] 

j has (4, 4) dimensions 

j is an object of type: <class 'numpy.ndarray'> 

The elements in j are int32 type 



NumPy also allows you to create ndarrays that have evenly spaced values within a given interval. NumPy's *np.arange()* function is very versatile and can be used with either *one*, *two*, or *three* arguments. Below we will see examples of each case and how they are used to create different kinds of ndarrays.

Let's start by using *np.arange()* with only one argument. When used with only one argument, *np.arange(N)* will create a *rank 1* ndarray with consecutive integers between 0 and N - 1. Therefore, notice that if I want an array to have integers between 0 and 9, I have to use N = 10, NOT N = 9, as in the example below:

In [22]:
# We create a rank 1 ndarray that has sequential integers from 0 to 9
k = np.arange(10)

# We print the ndarray
print(k, "\n")

# We print information about the ndarray
print('k has dimensions:', k.shape, "\n")
print('k is an object of type:', type(k), "\n")
print('The elements in k are of type:', k.dtype, "\n") 

[0 1 2 3 4 5 6 7 8 9] 

k has dimensions: (10,) 

k is an object of type: <class 'numpy.ndarray'> 

The elements in k are of type: int32 



When only one argument is provided above, it is considered the *stop*. When used with two arguments, np.arange(start,stop) will create a rank 1 ndarray with evenly spaced values within the half-open interval (start, stop). This means the evenly spaced numbers will include start but exclude stop. This uses the slicing concept of python list. Let's see an example

In [23]:
# We create a rank 1 ndarray that has sequential integers from 4 to 9.
l = np.arange(4,9)

#We print the ndarray
print(l, "\n")

#we print information about the ndarray
print("l has a dimension of:", l.shape, "\n")
print("l is an object type:", type(l), "\n")
print('The elements in k are of type:', k.dtype, "\n") 
print("the size of l is:", l.size, "\n") #the number of element in the array

#the function np.arange(4,10) generates a sequence of integers with 4 inclusive and 10 exclusive.

[4 5 6 7 8] 

l has a dimension of: (5,) 

l is an object type: <class 'numpy.ndarray'> 

The elements in k are of type: int32 

the size of l is: 5 



Finally, when used with three arguments, np.arange(start,stop,step) will create a rank 1 ndarray with evenly spaced values within the half-open interval (start, stop) with step being the distance between two adjacent values. Let's see an example:

In [24]:
# We create a rank 1 ndarray that has evenly spaced integers from 1 to 13 in steps of 3.
m = np.arange(1,14,3)

# We print the ndarray
print(m)

# We print information about the ndarray
print('m has dimensions:', m.shape, "with a size of:", m.size, "\n")
print('m is an object of type:', type(m), "\n")
print('The elements in m are of type:', m.dtype, "\n")
#We can see that m has sequential integers between 1 and 13 but the difference between all adjacent values is 3.

[ 1  4  7 10 13]
m has dimensions: (5,) with a size of: 5 

m is an object of type: <class 'numpy.ndarray'> 

The elements in m are of type: int32 



Even though the *np.arange()* function allows for non-integer steps, such as 0.3, the output is usually inconsistent, due to the finite floating point precision. For this reason, in the cases where non-integer steps are required, it is usually better to use the function **np.linspace()**. 

The **np.linspace(start, stop, N)** function returns N evenly spaced numbers over the closed interval (start, stop). This means that **both the start and the stop values are included (it returns both the start and stop values).** We should also note the *np.linspace()* function needs to be called with at least two arguments in the form np.linspace(start,stop). In a case where the third argument is not provided, the default number of elements in the specified interval will be N = 50.

The reason *np.linspace()* works better than the *np.arange()* function, is that np.linspace() uses the number of elements we want in a particular interval, instead of the step between values. Let's see some examples:

In [25]:
# We create a rank 1 ndarray that has sequential integers from 4 to 9 using linspace.
l = np.linspace(4,9)

#We print the ndarray
print(l, "\n")

[4.         4.10204082 4.20408163 4.30612245 4.40816327 4.51020408
 4.6122449  4.71428571 4.81632653 4.91836735 5.02040816 5.12244898
 5.2244898  5.32653061 5.42857143 5.53061224 5.63265306 5.73469388
 5.83673469 5.93877551 6.04081633 6.14285714 6.24489796 6.34693878
 6.44897959 6.55102041 6.65306122 6.75510204 6.85714286 6.95918367
 7.06122449 7.16326531 7.26530612 7.36734694 7.46938776 7.57142857
 7.67346939 7.7755102  7.87755102 7.97959184 8.08163265 8.18367347
 8.28571429 8.3877551  8.48979592 8.59183673 8.69387755 8.79591837
 8.89795918 9.        ] 



In [7]:
# We create a rank 1 ndarray that has 10 integers evenly spaced between 0 and 25.
m = np.linspace(0,25,10)

# We print the ndarray
print(m, "\n")

# We print information about the ndarray
print('m has dimensions:', m.shape, "\n")
print('m is an object of type:', type(m), "\n")
print('The elements in m are of type:', m.dtype)

[ 0.          2.77777778  5.55555556  8.33333333 11.11111111 13.88888889
 16.66666667 19.44444444 22.22222222 25.        ] 

m has dimensions: (10,) 

m is an object of type: <class 'numpy.ndarray'> 

The elements in m are of type: float64


As we can see from the above example, the function np.linspace(0,25,10) returns an ndarray with 10 evenly spaced numbers in the closed interval (0, 25). We can also see that both the start and end points, 0 and 25 in this case, are included. However, you can let the endpoint of the interval be excluded (just like in the np.arange() function) by setting the keyword endpoint = False in the np.linspace() function. Let's create the same x ndarray we created above but now with the endpoint excluded:

In [137]:
# We create a rank 1 ndarray that has 10 integers evenly spaced between 0 and 25,
# with 25 excluded.
n = np.linspace(0,25,10, endpoint = False)

# We print the ndarray
print('n = ', n, "\n")

# We print information about the ndarray
print('n has dimensions:', n.shape, "\n")
print('n is an object of type:', type(n), "\n")
print('The elements in n are of type:', n.dtype,) 

n =  [ 0.   2.5  5.   7.5 10.  12.5 15.  17.5 20.  22.5] 

n has dimensions: (10,) 

n is an object of type: <class 'numpy.ndarray'> 

The elements in n are of type: float64


We can use functions discussed previously to create *rank 2* ndarrays of any shape by combining them with the *np.reshape()* function. The *np.reshape(ndarray, new_shape)* function converts the given ndarray into the specified new_shape. 

It is important to note that the new_shape should be compatible with the number of elements in the given ndarray. For example, you can convert a *rank 1* ndarray with 6 elements, into a 3 x 2 rank 2 ndarray, or a 2 x 3 rank 2 ndarray, since both of these rank 2 arrays will have a total of 6 elements. However, you can't reshape the *rank 1* ndarray with 6 elements into a 3 x 3 *rank 2* ndarray, since this *rank 2* array will have 9 elements, which is greater than the number of elements in the original ndarray. Let's see some examples:

In [140]:
# We create a rank 1 ndarray with sequential integers from 0 to 19
n = np.arange(20)

# We print x
print('Original n =', n, "\n")


# We reshape x into a 4 x 5 ndarray 
n = np.reshape(n, (4,5)) # np.reshape(ndarray, new_shape)
#n = np.reshape(n, (4,4)) #an attempt like this returns: ValueError: cannot reshape array of size 20 into shape (4,4) 

# We print the reshaped x
print('Reshaped n = \n', n, "\n")

# We print information about the reshaped x
print('n has dimensions:', n.shape, "\n")
print('n is an object of type:', type(n), "\n")
print('The elements in n are of type:', n.dtype) 

Original n = [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19] 

Reshaped n = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]] 

n has dimensions: (4, 5) 

n is an object of type: <class 'numpy.ndarray'> 

The elements in n are of type: int32


One great feature about NumPy, is that some functions can also be applied as methods. This allows us to apply different functions in sequence in just one line of code. ndarray methods are similar to ndarray attributes in that they are both applied using dot notation (.). Let's see how we can accomplish the same result as in the above example, but in just one line of code:

In [143]:
# We create a a rank 1 ndarray with sequential integers from 0 to 19 and
# reshape it to a 4 x 5 array 
n = np.arange(20).reshape(4, 5)

# We print Y
print('n = \n', n, "\n")

# We print information about Y
print('n has dimensions:', n.shape, "\n")
print('Y is an object of type:', type(Y), "\n")
print('The elements in Y are of type:', Y.dtype, "\n") 

n = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]] 

n has dimensions: (4, 5) 

Y is an object of type: <class 'numpy.ndarray'> 

The elements in Y are of type: int32 



We can also combine *reshape()* with *np.linspace()* to create *rank 2* arrays, as shown in the next example.

In [27]:
# We create a rank 1 ndarray with 10 integers evenly spaced between 0 and 50,
# with 50 excluded. We then reshape it to a 5 x 2 ndarray
p = np.linspace(0,50,10, endpoint=False).reshape(5,2)

# We print p
print()
print('p= \n', p)
print()

# We print information about X
print('p has', p.shape, 'dimensions')
print('p is an object of type:', type(p))
print('The elements in p are of type:', p.dtype)


p= 
 [[ 0.  5.]
 [10. 15.]
 [20. 25.]
 [30. 35.]
 [40. 45.]]

p has (5, 2) dimensions
p is an object of type: <class 'numpy.ndarray'>
The elements in p are of type: float64


The last type of ndarrays we are going to create are *random ndarrays*. Random ndarrays are arrays that contain random numbers. Often in Machine Learning, you need to create random matrices, for example, when **initializing the weights of a Neural Network**. NumPy offers a variety of random functions to help us create random ndarrays of any shape.

Let's start by using the np.random.random(shape) function to create an ndarray of the given shape with random floats in the half-open interval (0.0, 1.0). The np.random(to access the random module in numpy).random(to access the function in the module)

In [3]:
import numpy as np
# We create a 3 x 3 ndarray with random floats in the half-open interval [0.0, 1.0).
X = np.random.random((3,3)) # I observed from my 3rd note that any cell having the random type of ndarray constantly
# changes values

# We print X
print()
print('X = \n', X)
print()

# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in x are of type:', X.dtype)


X = 
 [[0.68370861 0.42011609 0.7180827 ]
 [0.44196427 0.57643192 0.8971677 ]
 [0.88613531 0.38481896 0.89320338]]

X has dimensions: (3, 3)
X is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: float64


NumPy also allows us to create ndarrays with random integers within a particular interval. The function np.random.randint(start, stop, size = shape) creates an ndarray of the given shape with random integers in the half-open interval (start, stop). Let's see an example:

In [5]:
# We create a 3 x 2 ndarray with random integers in the half-open interval (4, 15)
X = np.random.randint(4,15,size=(3,2))

# We print X
print()
print('X = \n', X)
print()

# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)


X = 
 [[ 8 12]
 [ 9  9]
 [13 14]]

X has dimensions: (3, 2)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: int32


In some cases, you may need to create ndarrays with random numbers that satisfy certain statistical properties. For example, you may want the random numbers in the ndarray to have an average of 0. NumPy allows you create random ndarrays with numbers drawn from various probability distributions. 

The function np.random.normal(mean, standard deviation, size=shape), the example below creates an ndarray with the given shape that contains random numbers picked from a normal (Gaussian) distribution with the given mean and standard deviation. Let's create a 1,000 x 1,000 ndarray of random floating point numbers drawn from a normal distribution with a mean (average) of zero and a standard deviation of 0.1.



In [153]:
# We create a 1000 x 1000 ndarray of random floats drawn from normal (Gaussian) distribution
# with a mean of zero and a standard deviation of 0.1.
X = np.random.normal(0, 0.1, size=(1000,1000))

# We print X
print()
print('X = \n', X)
print()

# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)
print('The elements in X have a mean of:', X.mean())
print('The maximum value in X is:', X.max())
print('The minimum value in X is:', X.min())
print('X has', (X < 0).sum(), 'negative numbers')
print('X has', (X > 0).sum(), 'positive numbers')


X = 
 [[ 0.03672655 -0.02052673  0.05692076 ...  0.05249922  0.166867
   0.09190048]
 [ 0.01246393  0.10276795 -0.06661881 ...  0.2818065   0.01402967
  -0.03909409]
 [-0.0742496  -0.02337644  0.0335185  ...  0.01191784  0.05738062
  -0.18644273]
 ...
 [ 0.11374781 -0.00636494 -0.16567695 ... -0.20473204  0.0971057
  -0.11319832]
 [-0.08284611 -0.1369556   0.17746438 ...  0.30001478 -0.06661675
  -0.00684479]
 [-0.06979884  0.22842724 -0.14542452 ...  0.03729527 -0.19619076
   0.05072677]]

X has dimensions: (1000, 1000)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64
The elements in X have a mean of: 7.216967131665424e-05
The maximum value in X is: 0.48698061594273273
The minimum value in X is: -0.4956678719803058
X has 499274 negative numbers
X has 500726 positive numbers


As we can see, the average of the random numbers in the ndarray is close to zero, both the maximum and minimum values in X are symmetric about zero (the average), and we have about the same amount of positive and negative numbers.